version: '3.8'

services:
  redis:
    image: redis:6.2-alpine
    container_name: redis
    restart: unless-stopped
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    volumes:
      - ./system/redis/redis.conf:/usr/local/etc/redis/redis.conf
      - ./system/redis/users.acl:/usr/local/etc/redis/users.acl
    
  web:
    build: .
    image: web
    container_name: web
    ports:
      - 5000:5000
      - 5678:5678
    command: python server.py run -h 0.0.0.0
    volumes:
      - .:/usr/src/app
    environment:
      - FLASK_DEBUG=1
      - APP_SETTINGS=server.config.config.DockerConfig
    depends_on:
      - redis

  worker:
    image: web
    command: python server.py run_worker
    volumes:
      - .:/usr/src/app
    environment:
      - APP_SETTINGS=server.config.config.DockerConfig
    depends_on:
      - redis



  # dashboard:
  #   # build: ./project/dashboard
  #   #image: dashboard
  #   image: eoranged/rq-dashboard
  #   container_name: dashboard
  #   ports:
  #     - 9181:9181
  #   #command: rq-dashboard -H redis
  #   depends_on:
  #     - redis
